module.exports = {
  env: {
    node: true,
    browser: true,
    es6: true
  },
  rules: {
    // style
    'array-bracket-newline': [2, { multiline: true }],
    'array-element-newline': [2, 'consistent'],
    'block-spacing': [2],
    'brace-style': [2, '1tbs'],
    'comma-spacing': [2, { before: false, after: true }],
    'eol-last': [2],
    'func-call-spacing': [2],
    'function-paren-newline': [2, 'multiline'],
    'id-blacklist': [2, 'data', 'list'], // 根据需要配置
    'id-match': [0, '^[A-z0-9]{2,}$'], // 根据需要配置
    'indent': [2, 2],
    'key-spacing': [2, { beforeColon: false, afterColon: true, mode: 'strict' }],
    'keyword-spacing': [2, { before: true, after: true }],
    'line-comment-position': [0],
    'linebreak-style': [0, 'unix'],
    'lines-around-comment': [0],
    'lines-between-class-members': [0],
    'max-depth': [2, { max: 5, maximum: 5 }],
    'max-len': [0, { code: 100, comments: 150 }],
    'max-lines': [1, { max: 300 }],
    'max-lines-per-function': [1, { max: 50 }],
    'max-nested-callbacks': [2, { max: 5, maximum: 5 }],
    'max-params': [0, { max: 10, maximum: 10 }],
    'multiline-ternary': [1, 'always-multiline'],
    'new-parens': [2],
    'newline-per-chained-call': [0],
    'no-inline-comments': [0],
    'no-mixed-spaces-and-tabs': [2],
    'no-multiple-empty-lines': [2, { max: 2 }],
    'no-new-object': [2],
    'no-trailing-spaces': [2, { skipBlankLines: true, ignoreComments: true }],
    'no-whitespace-before-property': [2],
    'nonblock-statement-body-position': [2, 'beside'],
    'object-curly-newline': [2, { multiline: true, consistent: true }],
    'object-curly-spacing': [2, 'always', { arraysInObjects: true, objectsInObjects: true }],
    'operator-linebreak': [2, 'before'],
    'padded-blocks': [0],
    'quotes': [2, 'single', { avoidEscape: true, allowTemplateLiterals: true }],
    'semi': [2, 'never'],
    'space-before-function-paren': [2, 'never'],
    'space-infix-ops': [2],
    'space-unary-ops': [2, { words: true, nonwords: false, overrides: {} }],
    'switch-colon-spacing': [2, { after: true, before: false }],
    // variable
    'no-delete-var': [2],
    'no-restricted-globals': [2, 'event'],
    'no-shadow-restricted-names': [2],
    'no-undef': [2],
    'no-unused-vars': [1],
    'no-use-before-define': [1, { functions: false, classes: false }],
    // logic
    'for-direction': [2],
    'no-cond-assign': [1, 'always'],
    'no-console': [1],
    'no-constant-condition': [2],
    'no-debugger': [2],
    'no-dupe-args': [2],
    'no-duplicate-case': [2],
    'no-empty': [2, { allowEmptyCatch: true }],
    'no-ex-assign': [2],
    'no-extra-semi': [1],
    'no-func-assign': [2],
    'no-irregular-whitespace': [2],
    'no-obj-calls': [2],
    'no-sparse-arrays': [2],
    'no-unreachable': [2],
    'no-unsafe-finally': [2],
    'no-unsafe-negation': [2],
    'use-isnan': [2],
    'valid-typeof': [2],
    // best practice
    'array-callback-return': [2],
    'default-case': [2],
    'eqeqeq': [2, 'smart'],
    'no-empty-pattern': [2],
    'no-fallthrough': [2],
    'no-global-assign': [2],
    'no-multi-spaces': [2],
    'no-param-reassign': [1, { props: true }],
    'no-with': [2],
    'yoda': [2, 'never'],
    // es6
    'arrow-spacing': [2],
    'no-class-assign': [2],
    'no-const-assign': [2],
    'no-dupe-class-members': [2],
    'no-duplicate-imports': [1],
    'no-new-symbol': [2],
    'no-this-before-super': [2],
    'no-var': [2],
    'prefer-const': [1], // 根据需要修改
    'prefer-rest-params': [2],
    'prefer-template': [1]
  }
}